import lazy_loader


__getattr__, __dir__, __all__ = lazy_loader.attach(
    __name__,
    submodules={
        'config',
        'controllers',
        'experiment_logic',
        'main',
        'rdp_client',
        'reanalysis',
        'rig-reconfig',
        'utils',
        'webapp',
    },
    submod_attrs={
        'config': [
            'BACKGROUND_COLOR',
            'BOUNDARY_COLOR',
            'BOUNDARY_WIDTH',
            'FLASH_COLOR',
            'FLASH_OFF_DURATION',
            'FLASH_ON_DURATION',
            'PHASE_1_DURATION',
            'PHASE_2_DURATION',
            'PRE_CODE',
            'ROI_TYPE',
            'SPLIT_TIMES',
        ],
        'controllers': [
            'CameraError',
            'SpinnakerCamera',
            'camera',
            'list_cameras',
            'video_writer',
        ],
        'experiment_logic': [
            'constants',
            'setup',
            'updates',
        ],
        'main': [
            'BACKGROUND_COLOR',
            'BOUNDARY_COLOR',
            'BOUNDARY_X',
            'BOUNDARY_Y',
            'SCALE_FACTOR',
            'SCREEN_SIZE',
            'args',
            'cameras',
            'clock',
            'commands_to_run',
            'config_dir',
            'crop',
            'crop_bounds',
            'data_dir',
            'debug',
            'delay_processing',
            'elapsed_time',
            'exp_data_dir',
            'exp_dir',
            'exp_name',
            'frame_metadata',
            'image',
            'jpg',
            'lossless',
            'n_frames',
            'parser',
            'repo_dir',
            'rig_config',
            'running',
            'screen',
            'split',
            'start_time',
            'stream',
        ],
        'rdp_client': [
            'unlock_and_unzip_file',
            'zip_and_lock_folder',
        ],
        'reanalysis': [
            'BOUNDARY_X',
            'BOUNDARY_Y',
            'SCALE_FACTOR',
            'SCREEN_SIZE',
            'args',
            'cap',
            'compress',
            'convert_to_avi',
            'crop',
            'data_dir',
            'elapsed_time',
            'exp_name',
            'fps',
            'frame_count',
            'image',
            'lossless',
            'parser',
            'points',
            'rig_config',
            'roi_set',
            'split',
            'temp_image',
            'timestamp',
            'video_file',
            'x_max',
            'x_min',
            'y_max',
            'y_min',
        ],
        'rig-reconfig': [
            'FPS',
            'args',
            'cameras',
            'parser',
            'projector_height',
            'projector_width',
            'repo_dir',
            'rig_config',
            'screen',
            'timestamp',
        ],
        'utils': [
            'draw_arc',
            'draw_circle',
            'draw_cubic_bezier',
            'draw_line',
            'draw_rectangle',
            'get_boolean_answer',
            'get_rectangle_points',
            'hex_to_rgb',
            'rect_fit',
            'relative_to_absolute',
        ],
        'webapp': [
            'HTML_TEMPLATE',
            'app',
            'index',
            'r',
            'stream',
        ],
    },
)

__all__ = ['BACKGROUND_COLOR', 'BOUNDARY_COLOR', 'BOUNDARY_WIDTH',
           'BOUNDARY_X', 'BOUNDARY_Y', 'CameraError', 'FLASH_COLOR',
           'FLASH_OFF_DURATION', 'FLASH_ON_DURATION', 'FPS', 'HTML_TEMPLATE',
           'PHASE_1_DURATION', 'PHASE_2_DURATION', 'PRE_CODE', 'ROI_TYPE',
           'SCALE_FACTOR', 'SCREEN_SIZE', 'SPLIT_TIMES', 'SpinnakerCamera',
           'app', 'args', 'camera', 'cameras', 'cap', 'clock',
           'commands_to_run', 'compress', 'config', 'config_dir', 'constants',
           'controllers', 'convert_to_avi', 'crop', 'crop_bounds', 'data_dir',
           'debug', 'delay_processing', 'draw_arc', 'draw_circle',
           'draw_cubic_bezier', 'draw_line', 'draw_rectangle', 'elapsed_time',
           'exp_data_dir', 'exp_dir', 'exp_name', 'experiment_logic', 'fps',
           'frame_count', 'frame_metadata', 'get_boolean_answer',
           'get_rectangle_points', 'hex_to_rgb', 'image', 'index', 'jpg',
           'list_cameras', 'lossless', 'main', 'n_frames', 'parser', 'points',
           'projector_height', 'projector_width', 'r', 'rdp_client',
           'reanalysis', 'rect_fit', 'relative_to_absolute', 'repo_dir', 'rig-
           reconfig', 'rig_config', 'roi_set', 'running', 'screen', 'setup',
           'split', 'start_time', 'stream', 'temp_image', 'timestamp',
           'unlock_and_unzip_file', 'updates', 'utils', 'video_file',
           'video_writer', 'webapp', 'x_max', 'x_min', 'y_max', 'y_min',
           'zip_and_lock_folder']
