import lazy_loader


__getattr__, __dir__, __all__ = lazy_loader.attach(
    __name__,
    submodules={
        'config',
        'controllers',
        'experiment_logic',
        'main',
        'rdp_client',
        'utils',
    },
    submod_attrs={
        'config': [
            'BACKGROUND_COLOR',
            'BOUNDARY_COLOR',
            'BOUNDARY_WIDTH',
            'EXP_REGION_X',
            'EXP_REGION_Y',
            'HEIGHT',
            'PHASE_1_DURATION',
            'PHASE_2_DURATION',
            'PHASE_3_DURATION',
            'PHYSICAL_X',
            'PHYSICAL_Y',
            'SHOW_BOUNDARY',
            'TRAIL_1_CENTER',
            'TRAIL_1_COLOR',
            'TRAIL_1_RADIUS',
            'TRAIL_1_WIDTH',
            'TRAIL_2_CENTER',
            'TRAIL_2_COLOR',
            'TRAIL_2_RADIUS',
            'TRAIL_2_WIDTH',
            'TRAIL_3_CENTER',
            'TRAIL_3_COLOR',
            'TRAIL_3_RADIUS',
            'TRAIL_3_WIDTH',
            'WIDTH',
        ],
        'controllers': [
            'CameraError',
            'SpinnakerCamera',
            'camera',
            'list_cameras',
            'video_writer',
        ],
        'experiment_logic': [
            'constants',
            'setup',
            'updates',
        ],
        'main': [
            'BACKGROUND_COLOR',
            'BOUNDARY_COLOR',
            'BOUNDARY_X',
            'BOUNDARY_Y',
            'SCALE_FACTOR',
            'SCREEN_SIZE',
            'args',
            'cameras',
            'clock',
            'data_dir',
            'debug',
            'elapsed_time',
            'exp_data_dir',
            'exp_dir',
            'exp_name',
            'parser',
            'repo_dir',
            'running',
            'screen',
            'start_time',
        ],
        'rdp_client': [
            'unlock_and_unzip_file',
            'zip_and_lock_folder',
        ],
        'utils': [
            'get_boolean_answer',
            'hex_to_rgb',
            'relative_to_absolute',
        ],
    },
)

__all__ = ['BACKGROUND_COLOR', 'BOUNDARY_COLOR', 'BOUNDARY_WIDTH',
           'BOUNDARY_X', 'BOUNDARY_Y', 'CameraError', 'EXP_REGION_X',
           'EXP_REGION_Y', 'HEIGHT', 'PHASE_1_DURATION', 'PHASE_2_DURATION',
           'PHASE_3_DURATION', 'PHYSICAL_X', 'PHYSICAL_Y', 'SCALE_FACTOR',
           'SCREEN_SIZE', 'SHOW_BOUNDARY', 'SpinnakerCamera', 'TRAIL_1_CENTER',
           'TRAIL_1_COLOR', 'TRAIL_1_RADIUS', 'TRAIL_1_WIDTH',
           'TRAIL_2_CENTER', 'TRAIL_2_COLOR', 'TRAIL_2_RADIUS',
           'TRAIL_2_WIDTH', 'TRAIL_3_CENTER', 'TRAIL_3_COLOR',
           'TRAIL_3_RADIUS', 'TRAIL_3_WIDTH', 'WIDTH', 'args', 'camera',
           'cameras', 'clock', 'config', 'constants', 'controllers',
           'data_dir', 'debug', 'elapsed_time', 'exp_data_dir', 'exp_dir',
           'exp_name', 'experiment_logic', 'get_boolean_answer', 'hex_to_rgb',
           'list_cameras', 'main', 'parser', 'rdp_client',
           'relative_to_absolute', 'repo_dir', 'running', 'screen', 'setup',
           'start_time', 'unlock_and_unzip_file', 'updates', 'utils',
           'video_writer', 'zip_and_lock_folder']
