# FUNDAMENTALS
SHOW_BOUNDARY = False
CONVERT_TO_AVI = False
ROI_TYPE = "rectangle" # "rectangle" or "circle"
BOUNDARY_COLOR = "#FFFFFF"
BOUNDARY_WIDTH = 1
BACKGROUND_COLOR = "#000000"

# TIME PARAMETERS
PHASE_1_DURATION = 5 # in seconds
PHASE_2_DURATION = 3 # in seconds
PHASE_3_DURATION = 5 # in seconds
SPLIT_TIMES = [PHASE_1_DURATION, PHASE_1_DURATION + PHASE_2_DURATION]

# CIRCULAR TRAIL PARAMETERS (PHASE 1)
TRAIL_1_COLOR = "#FF0000"
TRAIL_1_RADIUS = 2 # in inches
TRAIL_1_WIDTH = 0.05 # in inches
TRAIL_1_CENTER = (0.5, 0.5)

# CIRCULAR TRAIL PARAMETERS (PHASE 2)
TRAIL_2_COLOR = "#000000"
TRAIL_2_RADIUS = 0 # in inches
TRAIL_2_WIDTH = 0 # in inches
TRAIL_2_CENTER = (0.5, 0.5)

# CIRCULAR TRAIL PARAMETERS (PHASE 3)
TRAIL_3_COLOR = "#FF0000"
TRAIL_3_RADIUS = 2 # in inches
TRAIL_3_WIDTH = 0.05 # in inches
TRAIL_3_CENTER = (0.5, 0.5)